### ISSUE TITLE
Connect to Car via Bluetooth

### ISSUE THREAD

**Issue by markgras** [WebsterXC/digidash#1]
-bluetooth from ODB2 bluetooth dongle to Pi

**Comment by WebsterXC** [comment]
Mark was able to find a solution to keep the Bluetooth adapter and OBDII vehicle connected, but we still need to send/receive valid data. 

Progress is being made!

**Comment by markgras** [comment]
Communication via bluetooth sockets has been achieved. Data can be sent and received.
