### ISSUE TITLE
Develop an In-Vehicle Mounting Solution for DigiDash.

### ISSUE THREAD

**Issue by WebsterXC** [WebsterXC/digidash#20]
In addition to further refining the DigiDash case design, we'll also need a way to mount it securely when it comes time to test it in our vehicles.

**Comment by markgras** [comment]
The "iOttie Easy One Touch 2 Car Mount for iPhone & Smartphones" (https://www.iottie.com/Product/Detail/1139/iOttie-Easy-One-Touch-2-Car-Mount-for-iPhone-_-Smartphones) works very well!

**Comment by markgras** [comment]
Oh also, don't buy it from the official site. It's a lot cheaper elsewhere.
