### ISSUE TITLE
Kivy Startup Screen

### ISSUE THREAD

**Issue by WebsterXC** [WebsterXC/digidash#24]
Develop a startup screen / menu that displays the DigiDash logo (or anything, really), while the RPi is connecting to the car (approximately 3-5 seconds).

If the RPi can't connect to the vehicle the first time, it will keep trying for 4 more tries in 5 second intervals. If it can't connect at all, the startup screen should notify the user.

**Comment by davideva53** [comment]
This issue was deemed as "No Longer Needed".
