### ISSUE TITLE
Implement OBDII readiness check and DTC code reading.

### ISSUE THREAD

**Issue by mohdkhan95** [WebsterXC/digidash#40]

**Comment by WebsterXC** [comment]
Could you elaborate a bit on what you plan on doing here?

I'm not sure what a readiness check is.

**Comment by mohdkhan95** [comment]
One reason some vehicles cannot complete the Emissions-Check is the on board diagnostic (OBD II) system readiness monitors are not set. Frequently, this is caused by erasing the memory from the OBD system by either clearing any diagnostic trouble codes (DTC) or disconnecting the battery. If the cause of the original failure (that intially set the MIL on) has been repaired properly, the DTC(s) will clear and the MIL will go out when the OBD system performs tests on emissions control system. (Reference: OHIO environ......)

This feature checks that your readiness flags are set before having your vehicle emissions-tested. This can save you the aggrevation of being sent off to drive around and come back later. (Reference: Some website)

**Comment by WebsterXC** [comment]
Good stuff, thanks for the clarification! I'll be interested to see how you implement this. Personally I've failed inspections for stuff that this code would have been able to tell me beforehand.

**Comment by WebsterXC** [comment]
Scanning of diagnostic trouble codes (DTCs) has been implemented and the bitmask math has been tested to be correct. I also implemented the ability to clear the check engine light.
