### ISSUE TITLE
Adjusting the brightness of Touchscreen display [OPTIONAL FEATURE]

### ISSUE THREAD

**Issue by mohdkhan95** [WebsterXC/digidash#41]

**Comment by WebsterXC** [comment]
Careful before you dive into this too much, I think we may already have a Bash script that does this. I may have spoken too soon.

**Comment by mohdkhan95** [comment]
Yes. This is one the the last thing in my To-do list. Apple devices are already implementing this feature and quite frankly I like it. Trying to change the brightness manually could be annoying sometimes. I'll have the design ready, and possibly try it out at the end of Sprint 4 or towards the end of the semester. Anyone who is interested can implement it in their rPI.

**Comment by markgras** [comment]
The touchscreen's backlight brightness is an unsigned byte (aka 0-255). For manual adjustment, I suggest letting the user jump in intervals of 5 between 10 and 255. Anything below 10 is almost impossible to see, even in an utterly dark room.

**Comment by Just-Joe** [comment]
Could be tied to 2 menu button to brighten and darken and call your script in the background

**Comment by markgras** [comment]
Exactly what I was thinking :)

**Comment by mohdkhan95** [comment]
Team members have decided to implement a bash script on their RPi touchscreen instead of developing a circuitry (initial plan).

**Comment by markgras** [comment]
Khan, we've not yet completed integration of this script into our program. The script is written, but appropriate buttons still need to be added to the GUI. As such, I'm reopening this issue.

**Comment by markgras** [comment]
Brightness buttons are in a settings sub-menu. There are buttons for 0%, 25%, 50%, 75%, and 100% brightness.
