### ISSUE TITLE
Analog gauge angle conversion.

### ISSUE THREAD

**Issue by WebsterXC** [WebsterXC/digidash#49]
Analog gauges don't work correctly because the needle position is calculated in degrees, rather than coordinates bound to values.

Implement this!

**Comment by Just-Joe** [comment]
Just made a commit to fix this. Will need to test before we can close this issue.

**Comment by WebsterXC** [comment]
Radian conversion completed by Joe. I'm making sure the solution is scalable and correct. So far, analog gauges work as intended.

**Comment by Just-Joe** [comment]
Hmm didn't extensively test this. Ill check it out now. Although were you trying to read values in that were larger than the defined max from the ini. That would cause weird visuals. I can make case statements for out of defined bounds though. Or should this be handled by something else?

**Comment by WebsterXC** [comment]
No, I'm just an idiot and didn't fill out the Settings.ini file correctly. Analog gauges are scalable and super-responsive. Great work Joe!
