### ISSUE TITLE
Gather sample vehicle data

### ISSUE THREAD

**Issue by WebsterXC** [WebsterXC/digidash#8]
Since we're having difficulties with Bluetooth and connecting to the car through a RPi in general, a set of input CSV files will be helpful to test other pieces of our project. For instance, the GUI guys can use the files as input to test the gauge functionality.

Ideally a couple different CSV's should exist for different driving situations: casual driving, fast/tight turns and accelerations, 1/4 mile pull.

**Comment by mohdkhan95** [comment]
Until the reading/writing to bluetooth port is solved, the following files can be used to test GUI functionality: 

[scan10.zip](https://github.com/WebsterXC/digidash/files/518493/scan10.zip)
[scan13.zip](https://github.com/WebsterXC/digidash/files/518498/scan13.zip)
[scan6.zip](https://github.com/WebsterXC/digidash/files/518495/scan6.zip)
[scan7.zip](https://github.com/WebsterXC/digidash/files/518494/scan7.zip)
[scan14.zip](https://github.com/WebsterXC/digidash/files/518496/scan14.zip)
[scan4 (1).zip](https://github.com/WebsterXC/digidash/files/518497/scan4.1.zip)

A description of each file can be found in http://www.fordscorpio.co.uk/obd2info.htm

**Comment by mohdkhan95** [comment]
Excel File of sample data from OBD 2 scan. 

[Sample_Data_OBD2.zip](https://github.com/WebsterXC/digidash/files/518520/Sample_Data_OBD2.zip)

**Comment by WebsterXC** [comment]
Sample CSV (in .txt format) has been uploaded to /can/data/, but requires a proper parser to put the data in the correct data structure at the correct time.

**Comment by WebsterXC** [comment]
Parser finished. There was another issue for this by itself (oops!).
